### ISSUE TITLE
Users need to be able to create their own unique & private "Field Notes"

### ISSUE THREAD

**Issue by itsoliviasparks** [itsoliviasparks/touch-grass#26]
## Summary 
- Currently all users share a singular Field Notes page (to-do list)
- To correct, I need to add user authentication via Firebase to allow each user to have an individualized & private Field Notes page

## Sub-issues
- [ ] Utilize `localStorage` to allow users to use the app without an account
     - [ ] Add button to create an account after adding items as a guest. Transfer this data to their new account
- [ ] Add user auth via Google so that users can create an account & have persistent data
- [ ] Update UI of home page:
>  Would you like to check-in at the Ranger Station?
Yes, I'd like to access my persistent Field Notes (Log-in via Google)
No, I'll Leave No Trace (Continue as Guest)

## Other Things to Look at
- [ ] Double check UI of to-do list. Could this be improved?
- [ ] Any security updates needed?
